[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[functions.newsletter]
schedule = "36 19 * * *"  # Correct UTC conversion for 1:06 AM IST (19:36 UTC)



[dev]
  command = "npm run dev"
  port = 3000
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/subscribe"
  to = "/.netlify/functions/subscribe"
  status = 200



[[redirects]]
  from = "/view"
  to = "/.netlify/functions/view"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200