[functions]
  [functions.newsletter-background]
    source = "netlify/functions/newsletter-background.js"
    timeout = 900
    background = true
    schedule = "50 17 * * *"  # 11:20 PM IST

  [functions.newsletter]
    timeout = 10

# Schedule comment moved outside table declaration

[build]
  command = "npm install"
  functions = "netlify/functions"