[functions]
  newsletter-background = { source = "netlify/functions/newsletter-background.js", timeout = 900, background = true, schedule = "40 20 * * *" }
  newsletter = { timeout = 10 }

[build]
  command = "npm install"
  functions = "netlify/functions"