[functions]
  [functions.newsletter-background]
    source = "netlify/functions/newsletter-background.js"
    timeout = 900
    background = true

  [functions.newsletter]
    timeout = 10

  [functions.deploy-succeeded]
    source = "netlify/functions/deploy-succeeded.js"
    timeout = 30

[build]
  command = "npm install"
  functions = "netlify/functions"

[build.environment]
  NETLIFY_WEBHOOK_SECRET = "your-webhook-secret-here"