[functions]
  newsletter-background = "netlify/functions/newsletter-background.js"
  test-background = "netlify/functions/test-background.js"
  newsletter-background = { timeout = 900, background = true, schedule = "55 14 * * *" }
  newsletter = { timeout = 10 }

[build]
  command = "npm install"
  functions = "netlify/functions"