[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[functions.scheduled-newsletter]
schedule = "35 20 * * *"  # Correct UTC conversion for 2:05 AM IST (20:35 UTC)



[dev]
  command = "npm run dev"
  port = 3000
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/subscribe"
  to = "/.netlify/functions/subscribe"
  status = 200



[[redirects]]
  from = "/view"
  to = "/.netlify/functions/view"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200