[functions]
  [functions.newsletter-background]
    source = "netlify/functions/newsletter-background.js"
    timeout = 10

  [functions.newsletter]
    timeout = 10

  [functions.newsletter-test]
    source = "netlify/functions/newsletter-background.js"
    timeout = 10
    schedule = "40 19 * * *"  # 1:10 AM IST (19:40 UTC)


[build]
  command = "npm install"
  functions = "netlify/functions"