[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[functions]
  scheduled-newsletter = { schedule = "20 15 * * *" }  # 3:20 PM UTC (8:50 PM IST)

[[plugins]]
package = "@netlify/plugin-functions-schedule"

  [plugins.inputs]
  "scheduled-newsletter" = "20 15 * * *"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/subscribe"
  to = "/.netlify/functions/subscribe"
  status = 200



[[redirects]]
  from = "/view"
  to = "/.netlify/functions/view"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200